# Generated by Django 6.0.4 on 2026-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_budgetcycle_delete_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('study', 'Study'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
