# Generated by Django 6.0.4 on 2026-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_expense_title_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(null=True),
        ),
    ]
