# Generated by Django 6.0.4 on 2026-05-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcycle',
            name='limit_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
