# Generated by Django 6.0.4 on 2026-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_budgetcycle_limit_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcycle',
            name='current_day_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
